### ISSUE TITLE
Add contributors to Readme

### ISSUE THREAD

**Issue by yonasb** [africa-covid-19-response-toolkit/emergency-relief-package-tracker#8]

**Comment by yonasb** [comment]
@all-contributors please add @dafrica1 for code.

**Comment by yonasb** [comment]
@all-contributors please add @naody for code.

**Comment by fegul** [comment]
@all-contributors please add @AppLixirDev for ideas and projectManagement

**Comment by fegul** [comment]
@all-contributors please add @Dumbulo for ideas and projectManagement

**Comment by fegul** [comment]
@all-contributors please add @Dumbulo for ideas and projectManagement
